app/database/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()



app/__init__.py
from flask import Flask
from .config import Config
from .database.models import db
from .routes.main import main_bp
from .routes.auth import auth_bp
import os

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)

    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp)

    return app


'''


if __name__ == "__main__":
    app.run(debug=True)


'''

app/routes/auth.py
from flask import Blueprint, render_template,redirect,url_for,session,request
from app.database.models import db

auth_bp = Blueprint('auth_bp',__name__)

app/routes/main.py
from flask import Blueprint, render_template,redirect,url_for,session,request
from app.database.models import db

main_bp = Blueprint('main_bp',__name__)


@main_bp.route('/')
def index(): 
    return render_template('index.html')


app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title%}{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{url_for('main_bp.index')}}">myCompany</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('main_bp.index')}}">Home</a>
              </li>
          </div>
        </div>
      </nav>

    {% block body %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block body %}


{% endblock %}